# Generated by Django 3.1.4 on 2021-02-09 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0004_town_officer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.PositiveSmallIntegerField(choices=[(1, 'Paxta'), (2, "G'ala")])),
                ('crop_group', models.PositiveSmallIntegerField(choices=[(1, 'Texnik'), (2, 'Boshoqli'), (3, 'Dukkaklik')], null=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=20)),
                ('seed', models.CharField(max_length=30)),
                ('harvest_size', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contour', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locations.contour')),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('started_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('duration', models.DurationField()),
                ('crop', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.crop')),
            ],
        ),
        migrations.CreateModel(
            name='TaskProgress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('size', models.DecimalField(decimal_places=2, max_digits=20)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='core.task')),
            ],
        ),
    ]
