# Generated by Django 3.1.4 on 2021-02-19 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='crop',
        ),
        migrations.RemoveField(
            model_name='task',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='task',
            name='started_at',
        ),
        migrations.RemoveField(
            model_name='task',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='crop',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='crop_number',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Paxta'), (2, "G'ala")], null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='end_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='start_date',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.DeleteModel(
            name='TaskProgress',
        ),
    ]
