# Generated by Django 3.1.4 on 2021-02-19 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210219_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='date',
            field=models.DateField(),
        ),
    ]
