# Generated by Django 3.1.4 on 2021-03-07 11:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20210225_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop',
            name='crop_group',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='name',
        ),
        migrations.RemoveField(
            model_name='task',
            name='crop_number',
        ),
    ]
