# Generated by Django 3.1.4 on 2021-03-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20210307_1258'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropChoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('crop_group', models.PositiveSmallIntegerField(choices=[(1, 'Texnik'), (2, 'Boshoqli'), (3, 'Dukkaklik')])),
            ],
        ),
    ]
