# Generated by Django 3.1.4 on 2021-03-07 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_task_crop_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='crop_choice',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='core.cropchoice'),
        ),
    ]
