# Generated by Django 3.1.4 on 2021-03-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_crop_crop_choice'),
    ]

    operations = [
        migrations.AddField(
            model_name='crop',
            name='year',
            field=models.IntegerField(null=True),
        ),
    ]
