# Generated by Django 3.1.4 on 2021-03-09 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_crop_year'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskprogress',
            name='size',
            field=models.DecimalField(decimal_places=2, max_digits=20, null=True),
        ),
    ]
