# Generated by Django 3.1.4 on 2021-03-09 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210309_1421'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='taskprogress',
            unique_together={('task', 'crop', 'date')},
        ),
    ]
