# Generated by Django 3.1.4 on 2021-02-19 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210209_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='roles',
            field=models.ManyToManyField(blank=True, to='accounts.Role'),
        ),
    ]
