# Generated by Django 3.1.4 on 2021-03-01 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20210219_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='region',
            field=models.PositiveSmallIntegerField(choices=[(8, 'Qashqadaryo'), (2, 'Andijan')], default=8),
        ),
        migrations.AlterField(
            model_name='role',
            name='id',
            field=models.PositiveSmallIntegerField(choices=[(2, 'governor'), (3, 'editor'), (4, 'district_officer'), (5, 'town_officer'), (6, 'supervisor'), (7, 'farmer')], primary_key=True, serialize=False),
        ),
    ]
