# Generated by Django 3.1.4 on 2021-03-05 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20210301_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='account',
            name='roles',
        ),
    ]
