# Generated by Django 3.1.4 on 2021-03-05 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_account_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
