# Generated by Django 3.1.4 on 2021-02-09 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('region', models.PositiveSmallIntegerField(choices=[(8, 'Qashqadaryo'), (2, 'Andijan')])),
            ],
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locations.district')),
            ],
        ),
        migrations.CreateModel(
            name='Contour',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('region', models.PositiveSmallIntegerField(choices=[(8, 'Qashqadaryo'), (2, 'Andijan')])),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locations.district')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='locations.town')),
            ],
        ),
    ]
