# Generated by Django 3.1.4 on 2021-02-09 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contour',
            name='farmer',
            field=models.ForeignKey(limit_choices_to={'roles__id': 7}, null=True, on_delete=django.db.models.deletion.RESTRICT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contour',
            name='supervisor',
            field=models.ForeignKey(limit_choices_to={'roles__id': 6}, null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='supervising_contours', to=settings.AUTH_USER_MODEL),
        ),
    ]
