# Generated by Django 3.1.4 on 2021-02-09 13:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('locations', '0002_auto_20210209_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='district',
            name='officer',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
