# Generated by Django 3.1.4 on 2021-02-19 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20210209_1411'),
        ('locations', '0005_auto_20210219_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contour',
            name='farmer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, to='accounts.farmer'),
        ),
        migrations.AlterField(
            model_name='contour',
            name='supervisor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.RESTRICT, related_name='supervising_contours', to='accounts.localsupervisor'),
        ),
    ]
