# Generated by Django 3.1.4 on 2021-03-08 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locations', '0008_auto_20210305_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contour',
            name='district',
        ),
    ]
